In [9]:
import numpy as np

In [10]:
# validity check sudoku
def check_pos_val(y, x, val):
    global field
    # check row of pos
    for i in range(9):
        if field[y][i] == val:
            return False
    # check col of pos
    for i in range(9):
        if field[i][x] == val:
            return False
    # check box of pos
    y0 = (y//3)*3
    x0 = (x//3)*3
    for i in range(3):
        for j in range(3):
            if field[y0+i][x0+j] == val:
                return False
    # if all checks got through, the val is possible for pos
    return True

In [17]:
def solve():
    global field
    for y in range(9):
        for x in range(9):
            if field[y][x] == 0:
                for val in range(1,10):
                    if check_pos_val(y, x, val):
                        field[y][x] = val
                        solve()
                        field[y][x] = 0
                return
    print(field)

In [18]:
path_to_sudoku_field = '../data/sudoku_field.txt'

In [19]:
field = np.loadtxt(path_to_sudoku_field, dtype=int)

In [20]:
field

array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
       [6, 0, 0, 1, 9, 5, 0, 0, 0],
       [0, 9, 8, 0, 0, 0, 0, 6, 0],
       [8, 0, 0, 0, 6, 0, 0, 0, 3],
       [4, 0, 0, 8, 0, 3, 0, 0, 1],
       [7, 0, 0, 0, 2, 0, 0, 0, 6],
       [0, 6, 0, 0, 0, 0, 2, 8, 0],
       [0, 0, 0, 4, 1, 9, 0, 0, 5],
       [0, 0, 0, 0, 8, 0, 0, 7, 9]])

In [21]:
check_pos_val(4, 4, 5)

True

In [22]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
